# LUNA16 2D 0-axis Dataset Configuration
train:
  image_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/LUNA16/train/images_2D_0axis/
  mask_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/LUNA16/train/masks_2D_0axis/
  augment: true
  normalize: true
  mean: [-593.9970]
  std: [417.0208]
val:
  image_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/val/images_2D_0axis/
  mask_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/val/masks_2D_0axis/
  augment: false
  normalize: true
  mean: [-593.9970]
  std: [417.0208]