# Splits 2D 0-axis Dataset Configuration
train:
  image_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/train/images_2D_2axis/
  mask_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/train/masks_2D_2axis/
  augment: true
  normalize: true
  mean: [-493.0376]
  std: [443.1897]
val:
  image_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/val/images_2D_2axis/
  mask_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/val/masks_2D_2axis/
  augment: false
  normalize: true
  mean: [-493.0376]
  std: [443.1897]