# Splits 2D 0-axis Dataset Configuration
train:
  image_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/train/images_2D_0axis/
  mask_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/train/masks_2D_0axis/
  augment: true
  normalize: true
val:
  image_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/val/images_2D_0axis/
  mask_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/val/masks_2D_0axis/
  augment: false
  normalize: true