test:
  image_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/val/images_2D_0axis/
  mask_dir: /radraid2/dongwoolee/VNet_LungNoduleSeg/richard/data/splits/val/masks_2D_0axis/
  augment: false
  normalize: true
  mean: [-493.0376]
  std: [443.1897]